### ISSUE TITLE
`do.call()` in `shiny_vector_filter()`

### ISSUE THREAD

**Issue by seb09** [dgkf/shinyDataFilter#7]
Hi Doug,

I've been looking for a filtering module like that for quite some time now. Loving your package. Very nice work! :-)

I stumbled over a little bit of an inconvenience, when trying to use your package within my package (a shiny app built with golem). The `shinyDataFilter` package needs to be attached when using it in another package, i.e. it has to be put in the *Depends:* field of the DESCRIPTION file, which is something I'm always trying to avoid. If it is not attached, there is an error, when a filter is added: `can't find function 'shiny_vector_filter'`

The reason for that seems to be a code line in `shiny_vector_filter()`

https://github.com/dgkf/shinyDataFilter/blob/43e158722098fe3169bfee20a4792a5e6d78cf7e/R/shiny_vector_filter.R#L92

which in my understanding requires the function `shiny_vector_filter()` to be present in the global environment. All package functions are imported into the namespace of my package (i.e. `@import shinyDataFilter`), but that does not help with regard to `do.call()`. 

Changing only this particular code line to 

`do.call(shinyDataFilter::shiny_vector_filter, args, envir = .GlobalEnv)`

did the trick for me and everything worked like a charm.

Would that be something that you would consider changing? There might of course also be a more elegant solution.

Best,
Sebastian :-)

**Comment by dgkf** [comment]
Hi Sebastian, thanks for the note! This is really helpful. 

The reason it's written this way is to make it easy to extend (well... theoretically... apparently it's not hitting that mark :smile:). The hope was that users could add their own `shiny_vector_filter.my_data_class` function to introduce custom filters without having to contribute the code directly to the `shinyDataFilter` package. 

To do this, we need to dispatch on the function name in the global environment. However, as you've identified, the function will not exist in the global environment if it hasn't been attached! I can add in a check that the function name exists before we attempt to call it, and otherwise call the function from within the `shinyDataFilter` namespace.

Many thanks for the diligent inspection!

**Comment by dgkf** [comment]
It should be fixed now, please open another issue if you have any more issues with it.
